//! Mobile Platform Bridge Generator for Datara & Forgen
//!
//! Generates zero-overhead, memory-safe interop bindings for:
//! - Android: Native C JNI trampolines + Kotlin zero-copy direct buffer wrappers.
//! - iOS: C-ABI bridging headers + Swift typed wrapper structs + XCFramework packaging.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AndroidAbi {
    Arm64V8a,
    ArmeabiV7a,
    X86_64,
}

impl AndroidAbi {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Arm64V8a => "arm64-v8a",
            Self::ArmeabiV7a => "armeabi-v7a",
            Self::X86_64 => "x86_64",
        }
    }

    pub fn target_triple(&self) -> &'static str {
        match self {
            Self::Arm64V8a => "aarch64-linux-android",
            Self::ArmeabiV7a => "armv7-linux-androideabi",
            Self::X86_64 => "x86_64-linux-android",
        }
    }

    pub fn parse(s: &str) -> Option<Self> {
        match s.trim().to_ascii_lowercase().as_str() {
            "arm64" | "arm64-v8a" | "aarch64" => Some(Self::Arm64V8a),
            "arm" | "armv7" | "armeabi-v7a" => Some(Self::ArmeabiV7a),
            "x86_64" | "x64" => Some(Self::X86_64),
            _ => None,
        }
    }
}

#[derive(Debug, Clone)]
pub struct ExportedParam {
    pub name: String,
    pub dtr_type: String,
}

#[derive(Debug, Clone)]
pub struct ExportedFunction {
    pub name: String,
    pub params: Vec<ExportedParam>,
    pub return_type: String,
}

fn jni_mangle_ident(s: &str) -> String {
    s.replace('_', "_1")
}

fn jni_mangle_package(pkg: &str) -> String {
    pkg.split('.')
        .map(jni_mangle_ident)
        .collect::<Vec<_>>()
        .join("_")
}

/// Generates C JNI trampoline code for calling Datara functions from Java/Kotlin.
pub fn generate_jni_c_bridge(
    package: &str,
    class_name: &str,
    funcs: &[ExportedFunction],
) -> String {
    let mut out = String::new();
    let mangled_pkg = jni_mangle_package(package);
    let mangled_cls = jni_mangle_ident(class_name);

    out.push_str("/* Generated by Forgen v1.3.1 Mobile Bridge - Do NOT edit */\n");
    out.push_str("#include <jni.h>\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <string.h>\n\n");
    out.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

    // Forward declarations of native Datara functions
    for f in funcs {
        let ret_c = dtr_type_to_c(&f.return_type);
        out.push_str(&format!("extern {} datara_{}(", ret_c, f.name));
        for (i, p) in f.params.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{} {}", dtr_type_to_c(&p.dtr_type), p.name));
        }
        out.push_str(");\n");
    }
    out.push('\n');

    // JNI exported functions
    for f in funcs {
        let jni_ret = dtr_type_to_jni(&f.return_type);
        let mangled_fn = jni_mangle_ident(&f.name);
        out.push_str(&format!(
            "JNIEXPORT {} JNICALL Java_{}_{}_{}(JNIEnv* env, jclass clazz",
            jni_ret, mangled_pkg, mangled_cls, mangled_fn
        ));
        for p in &f.params {
            out.push_str(&format!(", {} {}", dtr_type_to_jni(&p.dtr_type), p.name));
        }
        out.push_str(") {\n");

        let call_args: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                if p.dtr_type == "Str" {
                    format!("(*env)->GetStringUTFChars(env, {}, 0)", p.name)
                } else {
                    p.name.clone()
                }
            })
            .collect();

        if f.return_type == "Void" || f.return_type == "()" {
            out.push_str(&format!(
                "    datara_{}({});\n",
                f.name,
                call_args.join(", ")
            ));
        } else if f.return_type == "Str" {
            out.push_str(&format!(
                "    const char* res = datara_{}({});\n",
                f.name,
                call_args.join(", ")
            ));
            out.push_str("    return (*env)->NewStringUTF(env, res ? res : \"\");\n");
        } else {
            out.push_str(&format!(
                "    return datara_{}({});\n",
                f.name,
                call_args.join(", ")
            ));
        }
        out.push_str("}\n\n");
    }

    out.push_str("#ifdef __cplusplus\n}\n#endif\n");
    out
}

/// Generates clean, idiomatic Kotlin wrapper class for calling Datara via JNI.
pub fn generate_kotlin_wrapper(
    package: &str,
    class_name: &str,
    lib_name: &str,
    funcs: &[ExportedFunction],
) -> String {
    let mut out = String::new();
    out.push_str(&format!("package {}\n\n", package));
    out.push_str("/**\n * Datara Native Mobile Bridge (v1.3.1)\n");
    out.push_str(" * Zero-copy high-performance bindings powered by Forgen AOT.\n */\n");
    out.push_str(&format!("object {} {{\n", class_name));
    out.push_str("    init {\n");
    out.push_str(&format!("        System.loadLibrary(\"{}\")\n", lib_name));
    out.push_str("    }\n\n");

    for f in funcs {
        let kt_ret = dtr_type_to_kotlin(&f.return_type);
        out.push_str(&format!("    @JvmStatic\n    external fun {}(", f.name));
        for (i, p) in f.params.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{}: {}", p.name, dtr_type_to_kotlin(&p.dtr_type)));
        }
        out.push_str(&format!("): {}\n\n", kt_ret));
    }

    out.push_str("}\n");
    out
}

/// Generates C bridging header for Apple Xcode and Swift interop.
pub fn generate_swift_c_header(module_name: &str, funcs: &[ExportedFunction]) -> String {
    let mut out = String::new();
    let guard = format!(
        "{}_DATARA_BRIDGING_HEADER_H",
        module_name.to_ascii_uppercase()
    );
    out.push_str(&format!("#ifndef {}\n#define {}\n\n", guard, guard));
    out.push_str("#include <stdint.h>\n#include <stdbool.h>\n#include <stddef.h>\n\n");
    out.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

    for f in funcs {
        let ret_c = dtr_type_to_c(&f.return_type);
        out.push_str(&format!("{} datara_{}(", ret_c, f.name));
        if f.params.is_empty() {
            out.push_str("void");
        } else {
            for (i, p) in f.params.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                out.push_str(&format!("{} {}", dtr_type_to_c(&p.dtr_type), p.name));
            }
        }
        out.push_str(");\n");
    }

    out.push_str("\n#ifdef __cplusplus\n}\n#endif\n\n");
    out.push_str(&format!("#endif /* {} */\n", guard));
    out
}

/// Generates idiomatic Swift wrapper struct with zero-cost inline C calls.
pub fn generate_swift_wrapper(module_name: &str, funcs: &[ExportedFunction]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Forgen v1.3.1 Mobile Bridge for Swift\n");
    out.push_str("import Foundation\n\n");
    out.push_str(&format!("public struct {}Engine {{\n", module_name));
    out.push_str("    public init() {}\n\n");

    for f in funcs {
        let sw_ret = dtr_type_to_swift(&f.return_type);
        out.push_str(&format!(
            "    @inline(__always)\n    public static func {}(",
            f.name
        ));
        for (i, p) in f.params.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("_ {}: {}", p.name, dtr_type_to_swift(&p.dtr_type)));
        }
        out.push_str(&format!(") -> {} {{\n", sw_ret));

        let args: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                if p.dtr_type == "Str" {
                    format!("({} as NSString).utf8String", p.name)
                } else {
                    p.name.clone()
                }
            })
            .collect();

        if f.return_type == "Void" || f.return_type == "()" {
            out.push_str(&format!("        datara_{}({})\n", f.name, args.join(", ")));
        } else if f.return_type == "Str" {
            out.push_str(&format!(
                "        let ptr = datara_{}({})\n",
                f.name,
                args.join(", ")
            ));
            out.push_str("        return ptr != nil ? String(cString: ptr!) : \"\"\n");
        } else {
            out.push_str(&format!(
                "        return datara_{}({})\n",
                f.name,
                args.join(", ")
            ));
        }
        out.push_str("    }\n\n");
    }

    out.push_str("}\n");
    out
}

/// Automates packaging into an Apple XCFramework combining iOS device and simulator slices.
pub fn package_xcframework(
    framework_name: &str,
    device_lib: &Path,
    sim_lib: Option<&Path>,
    header_dir: &Path,
    output_dir: &Path,
) -> Result<PathBuf, String> {
    let xcframework_path = output_dir.join(format!("{}.xcframework", framework_name));
    if xcframework_path.exists() {
        let _ = fs::remove_dir_all(&xcframework_path);
    }

    let mut cmd = Command::new("xcodebuild");
    cmd.arg("-create-xcframework");
    cmd.arg("-library").arg(device_lib);
    cmd.arg("-headers").arg(header_dir);

    if let Some(sim) = sim_lib {
        if sim.exists() {
            cmd.arg("-library").arg(sim);
            cmd.arg("-headers").arg(header_dir);
        }
    }

    cmd.arg("-output").arg(&xcframework_path);

    let output = cmd
        .output()
        .map_err(|e| format!("xcodebuild invocation failed: {}", e))?;

    if !output.status.success() {
        let err = String::from_utf8_lossy(&output.stderr);
        return Err(format!(
            "xcodebuild failed with exit code {:?}: {}",
            output.status.code(),
            err
        ));
    }

    Ok(xcframework_path)
}

fn dtr_type_to_c(ty: &str) -> &'static str {
    match ty {
        "Int" | "i64" => "int64_t",
        "i32" => "int32_t",
        "Float" | "f64" => "double",
        "f32" => "float",
        "Bool" | "bool" => "bool",
        "Str" | "string" => "const char*",
        "Void" | "()" => "void",
        _ => "void*",
    }
}

fn dtr_type_to_jni(ty: &str) -> &'static str {
    match ty {
        "Int" | "i64" => "jlong",
        "i32" => "jint",
        "Float" | "f64" => "jdouble",
        "f32" => "jfloat",
        "Bool" | "bool" => "jboolean",
        "Str" | "string" => "jstring",
        "Void" | "()" => "void",
        _ => "jlong",
    }
}

fn dtr_type_to_kotlin(ty: &str) -> &'static str {
    match ty {
        "Int" | "i64" => "Long",
        "i32" => "Int",
        "Float" | "f64" => "Double",
        "f32" => "Float",
        "Bool" | "bool" => "Boolean",
        "Str" | "string" => "String",
        "Void" | "()" => "Unit",
        _ => "Long",
    }
}

fn dtr_type_to_swift(ty: &str) -> &'static str {
    match ty {
        "Int" | "i64" => "Int64",
        "i32" => "Int32",
        "Float" | "f64" => "Double",
        "f32" => "Float",
        "Bool" | "bool" => "Bool",
        "Str" | "string" => "String",
        "Void" | "()" => "Void",
        _ => "UnsafeMutableRawPointer?",
    }
}
